logs:
  configs:
    - name: default
      positions:
        filename: /tmp/positions.yaml
      scrape_configs:
        - job_name: starknet-remix-docker-logs
          static_configs:
            - targets: [localhost]
              labels:
                job: starknet-remix-docker-logs
                __path__: "${PROMTAIL_BASE_DIR}/logs/*"
      clients:
        - url: https://logs-prod-006.grafana.net/loki/api/v1/push
          basic_auth:
            username: ${PROMTAIL_USERNAME}
            password: ${PROMTAIL_PASSWORD}
